2025-02-22 14:50:41,646 INFO    MainThread:58922 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-22 14:50:41,647 INFO    MainThread:58922 [wandb_setup.py:_flush():67] Configure stats pid to 58922
2025-02-22 14:50:41,647 INFO    MainThread:58922 [wandb_setup.py:_flush():67] Loading settings from /Users/dganjali/.config/wandb/settings
2025-02-22 14:50:41,647 INFO    MainThread:58922 [wandb_setup.py:_flush():67] Loading settings from /Users/dganjali/Documents/GitHub/FinalCSP/reinforcement/tetris/wandb/settings
2025-02-22 14:50:41,647 INFO    MainThread:58922 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-22 14:50:41,647 INFO    MainThread:58922 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/dganjali/Documents/GitHub/FinalCSP/reinforcement/tetris/wandb/run-20250222_145041-a8fvq6hf/logs/debug.log
2025-02-22 14:50:41,647 INFO    MainThread:58922 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/dganjali/Documents/GitHub/FinalCSP/reinforcement/tetris/wandb/run-20250222_145041-a8fvq6hf/logs/debug-internal.log
2025-02-22 14:50:41,651 INFO    MainThread:58922 [wandb_init.py:init():761] calling init triggers
2025-02-22 14:50:41,652 INFO    MainThread:58922 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'exp_name': 'train', 'seed': 1, 'torch_deterministic': True, 'cuda': True, 'track': True, 'wandb_project_name': 'tetris_gymnasium', 'wandb_entity': None, 'capture_video': True, 'save_model': False, 'upload_model': False, 'hf_entity': '', 'env_id': 'tetris_gymnasium/Tetris', 'total_timesteps': 20000000, 'learning_rate': 0.0001, 'num_envs': 1, 'buffer_size': 1000000, 'gamma': 0.99, 'tau': 1.0, 'target_network_frequency': 1000, 'batch_size': 32, 'start_e': 1, 'end_e': 0.01, 'exploration_fraction': 0.1, 'learning_starts': 80000, 'train_frequency': 4, '_wandb': {'code_path': 'code/reinforcement/tetris/train.py'}}
2025-02-22 14:50:41,652 INFO    MainThread:58922 [wandb_init.py:init():784] starting backend
2025-02-22 14:50:41,652 INFO    MainThread:58922 [wandb_init.py:init():788] sending inform_init request
2025-02-22 14:50:41,677 INFO    MainThread:58922 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-02-22 14:50:41,677 INFO    MainThread:58922 [wandb_init.py:init():803] backend started and connected
2025-02-22 14:50:41,682 INFO    MainThread:58922 [wandb_init.py:init():896] updated telemetry
2025-02-22 14:50:41,711 INFO    MainThread:58922 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-22 14:50:41,958 INFO    MainThread:58922 [wandb_init.py:init():995] starting run threads in backend
2025-02-22 14:50:42,037 INFO    MainThread:58922 [wandb_run.py:_console_start():2377] atexit reg
2025-02-22 14:50:42,037 INFO    MainThread:58922 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-22 14:50:42,037 INFO    MainThread:58922 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-22 14:50:42,037 INFO    MainThread:58922 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-22 14:50:42,038 INFO    MainThread:58922 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-22 14:50:42,062 INFO    MainThread:58922 [wandb_run.py:_tensorboard_callback():1449] tensorboard callback: runs/train/zeta_kappa__1__1740253840, True
2025-02-22 14:50:42,240 WARNING MsgRouterThr:58922 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/Users/dganjali/.pyenv/versions/3.10.13/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-22 14:50:42,241 INFO    MsgRouterThr:58922 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
